### ISSUE TITLE
The endpoint popular doesn't work if the query param `size` is not provided

### ISSUE THREAD

**Issue by ElPicador** [lambdax-x/algolia-challenge#2]
The URL `/1/queries/popular/2015` renders a `400`. It should accept a default size of `10`

**Comment by lambdax-x** [comment]
Thanks @ElPicador, I mainly focused on data structures and I rushed a bit into the routing part of the HTTP service. I am currently working on a generic approach to match routes and handle requests with a set of macros. Declaring a route would look like: `route!(/1/queries/popular/(date: Date)?(size: usize) => handler_popular)`.

**Comment by lambdax-x** [comment]
I just published a crate for routing (https://crates.io/crates/rouste), I'll integrate it soon to handle routes better in this project.

**Comment by lambdax-x** [comment]
Solved by https://github.com/lambdax-x/algolia-challenge/commit/07f0d7343f35f5d7e1d2801c629a179777772207?diff=unified#diff-bfa17b8ec2b0aac77da5f96cbcbe4101R28.
